name: Deploy PokeAPI Distribuido

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Login a Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push backend-pokedex
        run: |
          cd backend-pokedex
          docker build -t arieling/backend-pokedex .
          docker push arieling/backend-pokedex

      - name: Build & Push backend-historial
        run: |
          cd ../backend-historial
          docker build -t arieling/backend-historial .
          docker push arieling/backend-historial

      - name: Build & Push frontend
        run: |
          cd ../poke-frontend
          docker build -t arieling/poke-frontend .
          docker push arieling/poke-frontend

  deploy-backend:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar backend-pokedex en EC2 instancia 1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY_BACKEND }}
          script: |
            docker pull arieling/backend-pokedex
            docker stop pokedex || true && docker rm pokedex || true
            docker run -d -p 3000:3000 --name pokedex arieling/backend-pokedex

  deploy-frontend:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar backend-historial y frontend en EC2 instancia 2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY_FRONTEND }}
          script: |
            docker pull arieling/backend-historial
            docker pull arieling/poke-frontend

            docker stop historial || true && docker rm historial || true
            docker stop frontend || true && docker rm frontend || true

            docker run -d -p 3001:3001 --name historial arieling/backend-historial
            docker run -d -p 80:3000 --name frontend arieling/poke-frontend
